
package com.devwithimagination.proxy.ws.three;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-2b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WarWSService", targetNamespace = "http://war.proxy.devwithimagination.com/", wsdlLocation = "https://dev-gf3.local/test/WarWSService?wsdl")
public class WarWSService
    extends Service
{

    private final static URL WARWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException WARWSSERVICE_EXCEPTION;
    private final static QName WARWSSERVICE_QNAME = new QName("http://war.proxy.devwithimagination.com/", "WarWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://dev-gf3.local/test/WarWSService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WARWSSERVICE_WSDL_LOCATION = url;
        WARWSSERVICE_EXCEPTION = e;
    }

    public WarWSService() {
        super(__getWsdlLocation(), WARWSSERVICE_QNAME);
    }

    public WarWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WARWSSERVICE_QNAME, features);
    }

    public WarWSService(URL wsdlLocation) {
        super(wsdlLocation, WARWSSERVICE_QNAME);
    }

    public WarWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WARWSSERVICE_QNAME, features);
    }

    public WarWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WarWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WarWS
     */
    @WebEndpoint(name = "WarWSPort")
    public WarWS getWarWSPort() {
        return super.getPort(new QName("http://war.proxy.devwithimagination.com/", "WarWSPort"), WarWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WarWS
     */
    @WebEndpoint(name = "WarWSPort")
    public WarWS getWarWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://war.proxy.devwithimagination.com/", "WarWSPort"), WarWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WARWSSERVICE_EXCEPTION!= null) {
            throw WARWSSERVICE_EXCEPTION;
        }
        return WARWSSERVICE_WSDL_LOCATION;
    }

}
