
package com.devwithimagination.proxy.ws.two;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-2b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloTwoWS", targetNamespace = "http://ws.proxy.devwithimagination.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloTwoWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHello", targetNamespace = "http://ws.proxy.devwithimagination.com/", className = "com.devwithimagination.proxy.ws.two.GetHello")
    @ResponseWrapper(localName = "getHelloResponse", targetNamespace = "http://ws.proxy.devwithimagination.com/", className = "com.devwithimagination.proxy.ws.two.GetHelloResponse")
    @Action(input = "http://ws.proxy.devwithimagination.com/HelloTwoWS/getHelloRequest", output = "http://ws.proxy.devwithimagination.com/HelloTwoWS/getHelloResponse")
    public String getHello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHelloWithAuth", targetNamespace = "http://ws.proxy.devwithimagination.com/", className = "com.devwithimagination.proxy.ws.two.GetHelloWithAuth")
    @ResponseWrapper(localName = "getHelloWithAuthResponse", targetNamespace = "http://ws.proxy.devwithimagination.com/", className = "com.devwithimagination.proxy.ws.two.GetHelloWithAuthResponse")
    @Action(input = "http://ws.proxy.devwithimagination.com/HelloTwoWS/getHelloWithAuthRequest", output = "http://ws.proxy.devwithimagination.com/HelloTwoWS/getHelloWithAuthResponse")
    public String getHelloWithAuth(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
