
package com.devwithimagination.proxy.ws.two;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-2b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HelloTwoWS", targetNamespace = "http://ws.proxy.devwithimagination.com/", wsdlLocation = "http://dev-ws.local/HelloTwoWS?wsdl")
public class HelloTwoWS_Service
    extends Service
{

    private final static URL HELLOTWOWS_WSDL_LOCATION;
    private final static WebServiceException HELLOTWOWS_EXCEPTION;
    private final static QName HELLOTWOWS_QNAME = new QName("http://ws.proxy.devwithimagination.com/", "HelloTwoWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://dev-ws.local/HelloTwoWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HELLOTWOWS_WSDL_LOCATION = url;
        HELLOTWOWS_EXCEPTION = e;
    }

    public HelloTwoWS_Service() {
        super(__getWsdlLocation(), HELLOTWOWS_QNAME);
    }

    public HelloTwoWS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), HELLOTWOWS_QNAME, features);
    }

    public HelloTwoWS_Service(URL wsdlLocation) {
        super(wsdlLocation, HELLOTWOWS_QNAME);
    }

    public HelloTwoWS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HELLOTWOWS_QNAME, features);
    }

    public HelloTwoWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloTwoWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HelloTwoWS
     */
    @WebEndpoint(name = "HelloTwoWSPort")
    public HelloTwoWS getHelloTwoWSPort() {
        return super.getPort(new QName("http://ws.proxy.devwithimagination.com/", "HelloTwoWSPort"), HelloTwoWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloTwoWS
     */
    @WebEndpoint(name = "HelloTwoWSPort")
    public HelloTwoWS getHelloTwoWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.proxy.devwithimagination.com/", "HelloTwoWSPort"), HelloTwoWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HELLOTWOWS_EXCEPTION!= null) {
            throw HELLOTWOWS_EXCEPTION;
        }
        return HELLOTWOWS_WSDL_LOCATION;
    }

}
